### ISSUE TITLE
Basebot URL unaccessible (https://basebot.ans.tools)

### ISSUE THREAD

**Issue by dewhurstwill** [ans-group/basebot#41]
**Describe the bug**
The URL https://basebot.ans.tools is no longer accessible

**To Reproduce**
1. Go to your browser of choice
2. Navigate to https://basebot.ans.tools

Hmmm… can't reach this pagebasebot.ans.tools’s server IP address could not be found.
ERR_NAME_NOT_RESOLVED

**Expected behavior**
Basebot documentation site loads

**Desktop (please complete the following information):**
 - OS: OSX 10.15.6
 - Browser Edge 
 - Version 84.0.522.63

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Maz
 - OS: IOS 14.0 (beta4)
 - Browser: Safari

**Comment by ceuk** [comment]
I've updated the URL to https://ans-group.github.io/basebot/
